apiVersion: apps/v1
kind: Deployment # Type de ressource kubernetes cree
metadata:
  name: github-action-k8s-deployment
spec:
  selector:
    matchLabels:
      app: github-action-k8s-deployment
  replicas: 5 # nombre de replica
  template:
    metadata:
      labels:
        app: github-action-k8s-deployment
    spec:
      containers:
        - name: github-action-k8s-deployment
          image: fayeyoussou/github-action # nom de l'image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # port de deployment