apiVersion: apps/v1
kind: Deployment # Type de ressource kubernetes crée
metadata:
  name: github-action-k8s-deployment
spec:
  selector:
    matchLabels:
      app: github-action-k8s-deployment
  replicas: 5 # Nombre de replicas
  template:
    metadata:
      labels:
        app: github-action-k8s-deployment
    spec:
      containers:
        - name: github-action-k8s-deployment
          image: fayeyoussou/github-action # image utilise
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster